### ISSUE TITLE
Update `Cert-manager`

### ISSUE THREAD

**Issue by kdcllc** [kdcllc/Bet.AspNetCore#147]
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-v1
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: email@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-v1
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
```
