### ISSUE TITLE
[DOTNETCORE] Adding support for DotNetCore Worker HealthChecks

### ISSUE THREAD

**Issue by kdcllc** [kdcllc/Bet.AspNetCore#84]
This functionality is not supported from the latest release. 

- [Define a TCP liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-tcp-liveness-probe)

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
```

- Use Named port

```yaml
ports:
- name: liveness-port
  containerPort: 8080
  hostPort: 8080

livenessProbe:
  httpGet:
    path: /healthz
    port: liveness-port
```
- [`TcpListiner`](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-tcp-services)

```csharp
using System;  
using System.Net.Sockets;  
using System.Text;  
  
public class TcpTimeServer {  
  
    private const int portNum = 13;  
  
    public static int Main(String[] args) {  
        bool done = false;  
  
        TcpListener listener = new TcpListener(portNum);  
  
        listener.Start();  
  
        while (!done) {  
            Console.Write("Waiting for connection...");  
            TcpClient client = listener.AcceptTcpClient();  
  
            Console.WriteLine("Connection accepted.");  
            NetworkStream ns = client.GetStream();  
  
            byte[] byteTime = Encoding.ASCII.GetBytes(DateTime.Now.ToString());  
  
            try {  
                ns.Write(byteTime, 0, byteTime.Length);  
                ns.Close();  
                client.Close();  
            } catch (Exception e) {  
                Console.WriteLine(e.ToString());  
            }  
        }  
  
        listener.Stop();  
  
        return 0;  
    }  
  
}
```

## Reference
- https://blog.tomkerkhove.be/2019/07/04/health-checks-with-openapi-specifications/
- https://github.com/glennc/worker
- https://github.com/aspnet/Extensions/issues/967
- https://gunnarpeipman.com/aspnet-core-health-checks/
- https://www.geeksforgeeks.org/how-to-terminate-a-thread-in-c-sharp/
